spring:
  application:
    name: config
  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://github.com/JKLeGend/springcloud-demo-config.git
          username:
          password:
#          clone-on-start: true
          search-paths: '/config/{application}'
