server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8001/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: debug