server:
  port: 9001
spring:
  cloud:
    gateway:
      routes:
        - id: retry_route
          uri: ${RIBBON_URL:http://localhost:8002}
          predicates:
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 1
                statuses: BAD_GATEWAY
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
logging:
  level:
    org.springframework.cloud.gateway: debug