server:
  port: 8000
spring:
  application:
    name: client-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
